### ISSUE TITLE
[모듈 추가] Kotlin - Discord 관련 Module 추가

### ISSUE THREAD

**Issue by patrick-mc** [Short-Kat/shortcode#3]
## 언어
> 무슨 언어인가요? (`ALLOWED_LANGUAGE.txt` 에 있는 언어 중 하나)

`Kotlin`, `Java`

## 모듈 이름
> 모듈 이름을 알려주세요 (`beautifulsoup`, `discord.py` 등등) (aliases 말고 정확한 이름을 입력해주세요)

- `Discord4J` or `JDA`
- Discord Library 가 허용되지 않을 경우, `Gson`

## 모듈이 무슨 기능이 있나요?
> 모듈의 기능을 알려주세요 (예: 요청의 결과를 편하게 볼수 있습니다)

- Discord wrapper in Java
- Json Library made by Google

## 확인
- [x] `ALLOWED_MODULES` 에 모듈이 포함되어 있지는 않나요?

**Comment by kiki7000** [comment]
만일 추가한다면 Java.txt Kotlin.txt  만들고 둘다 추가해주세요
@ditto7890 @minibox24

**Comment by minibox24** [comment]
Discord4J 자바, 코틀린에 추가했습니당
